### ISSUE TITLE
Can't use role on systems which permit execution in '/tmp' directory

### ISSUE THREAD

**Issue by RiccardoBoettcher** [deekayen/ansible-role-awscli2#2]
On hosts with a hardened OS (following CIS guidelines), the /tmp directory is mounted as non-executable. 
To use this role it must fully support a customized location for downloaded installer.

**Comment by guenhter** [comment]
The `/tmp` is defined as variable you can override any time.
Just define a different location for the variable `executable_temp_dir` and you should be good to go.

**Comment by RiccardoBoettcher** [comment]
Fix provided via #3, but no new release provided yet. @deekayen: can you please create a new release containing the MR?
